// Batteries
export const solarPanels = [
  {
    type: "Panels",
    name: "Mono-Crystalline Solar Panel 350W",
    description:
      "High-efficiency solar panel for residential and commercial use.",
    inStock: true,
    price: "₦150,000",
    discountPrice: "₦135,000",
    image: "/images/panel350w.png",
    location: "Enugu, Nigeria",
    details: {
      size: "1956 x 992 x 40 mm",
      weight: "19kg",
      warranty: "25 years",
      efficiency: "21%",
    },
  },
  {
    type: "Panels",
    name: "Poly-Crystalline Solar Panel 250W",
    description: "Durable and affordable option for homes and small offices.",
    inStock: true,
    price: "₦95,000",
    discountPrice: "₦85,000",
    image: "/images/panel250w.png",
    location: "Enugu, Nigeria",
    details: {
      size: "1640 x 992 x 35 mm",
      weight: "16kg",
      warranty: "20 years",
      efficiency: "18%",
    },
  },
  {
    type: "Panels",
    name: "Thin-Film Amorphous Silicon Panel 100W",
    description:
      "Lightweight and flexible solar panel suitable for portable and off-grid applications.",
    inStock: true,
    price: "₦45,000",
    discountPrice: "₦40,000",
    image: "/images/panel-thinfilm.png",
    location: "Enugu, Nigeria",
    details: {
      size: "1200 x 600 x 5 mm",
      weight: "7kg",
      warranty: "10 years",
      efficiency: "10%",
    },
  },
  {
    type: "Panels",
    name: "Cadmium Telluride (CdTe) Solar Panel 200W",
    description:
      "Cost-effective thin-film technology, ideal for utility-scale projects.",
    inStock: false,
    price: "₦80,000",
    discountPrice: "₦75,000",
    image: "/images/panel-cdte.png",
    location: "Enugu, Nigeria",
    details: {
      size: "1600 x 800 x 35 mm",
      weight: "14kg",
      warranty: "15 years",
      efficiency: "14%",
    },
  },
  {
    type: "Panels",
    name: "Copper Indium Gallium Selenide (CIGS) Panel 150W",
    description:
      "Flexible and lightweight panel with strong low-light performance.",
    inStock: true,
    price: "₦70,000",
    discountPrice: "₦65,000",
    image: "/images/panel-cigs.png",
    location: "Enugu, Nigeria",
    details: {
      size: "1400 x 700 x 4 mm",
      weight: "8kg",
      warranty: "15 years",
      efficiency: "16%",
    },
  },
  {
    type: "Panels",
    name: "Bifacial Mono-Crystalline Solar Panel 400W",
    description:
      "Generates power from both front and rear sides, boosting overall energy yield.",
    inStock: true,
    price: "₦200,000",
    discountPrice: "₦185,000",
    image: "/images/panel-bifacial.png",
    location: "Enugu, Nigeria",
    details: {
      size: "2010 x 1000 x 40 mm",
      weight: "21kg",
      warranty: "30 years",
      efficiency: "22%",
    },
  },
  {
    type: "Panels",
    name: "PERC Solar Panel 370W",
    description:
      "Passivated Emitter Rear Cell (PERC) technology for higher efficiency and better low-light performance.",
    inStock: true,
    price: "₦160,000",
    discountPrice: "₦148,000",
    image: "/images/panel-perc.png",
    location: "Enugu, Nigeria",
    details: {
      size: "1980 x 990 x 38 mm",
      weight: "20kg",
      warranty: "25 years",
      efficiency: "21.5%",
    },
  },
  {
    type: "Panels",
    name: "Half-Cut Solar Panel 450W",
    description:
      "Designed with half-cut cells to reduce power loss and improve efficiency.",
    inStock: true,
    price: "₦220,000",
    discountPrice: "₦200,000",
    image: "/images/panel-halfcut.png",
    location: "Enugu, Nigeria",
    details: {
      size: "2108 x 1048 x 40 mm",
      weight: "23kg",
      warranty: "25 years",
      efficiency: "22.3%",
    },
  },
  {
    type: "Panels",
    name: "Shingled Solar Panel 420W",
    description:
      "High-performance panel with overlapping cells for better aesthetics and output.",
    inStock: false,
    price: "₦210,000",
    discountPrice: "₦195,000",
    image: "/images/panel-shingled.png",
    location: "Enugu, Nigeria",
    details: {
      size: "2090 x 1020 x 40 mm",
      weight: "22kg",
      warranty: "25 years",
      efficiency: "22%",
    },
  },
  {
    type: "Panels",
    name: "Building Integrated Photovoltaic (BIPV) Panel",
    description:
      "Aesthetic solar solution integrated into roofs, facades, and windows.",
    inStock: true,
    price: "₦300,000",
    discountPrice: "₦280,000",
    image: "/images/panel-bipv.png",
    location: "Enugu, Nigeria",
    details: {
      size: "Customizable",
      weight: "Varies",
      warranty: "25 years",
      efficiency: "15–18%",
    },
  },
];

// Batteries
export const solarBatteries = [
  {
    type: "Batteries",
    name: "Lithium-Ion Solar Battery 5kWh",
    description:
      "Reliable storage battery with long lifecycle and fast charging.",
    inStock: true,
    price: "₦1,200,000",
    discountPrice: "₦1,080,000",
    image: "/images/battery5kwh.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Lithium-Ion",
      capacity: "5kWh",
      lifespan: "6000+ cycles",
      warranty: "10 years",
    },
  },
  {
    type: "Batteries",
    name: "Tubular Deep Cycle Battery 220Ah",
    description: "Affordable, heavy-duty battery for solar backup systems.",
    inStock: false,
    price: "₦250,000",
    discountPrice: "₦220,000",
    image: "/images/battery220ah.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Lead Acid Tubular",
      capacity: "220Ah",
      lifespan: "1500+ cycles",
      warranty: "3 years",
    },
  },
  {
    type: "Batteries",
    name: "AGM (Absorbent Glass Mat) Battery 200Ah",
    description:
      "Maintenance-free sealed lead-acid battery with spill-proof design.",
    inStock: true,
    price: "₦200,000",
    discountPrice: "₦185,000",
    image: "/images/battery-agm.png",
    location: "Enugu, Nigeria",
    details: {
      type: "AGM Lead Acid",
      capacity: "200Ah",
      lifespan: "1000+ cycles",
      warranty: "2 years",
    },
  },
  {
    type: "Batteries",
    name: "Gel Solar Battery 200Ah",
    description:
      "Sealed gel battery with deep discharge capability and minimal maintenance.",
    inStock: true,
    price: "₦220,000",
    discountPrice: "₦200,000",
    image: "/images/battery-gel.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Gel Lead Acid",
      capacity: "200Ah",
      lifespan: "1200+ cycles",
      warranty: "3 years",
    },
  },
  {
    type: "Batteries",
    name: "Nickel-Cadmium (NiCd) Solar Battery 1.2kWh",
    description:
      "Durable battery suitable for extreme temperatures and remote installations.",
    inStock: false,
    price: "₦500,000",
    discountPrice: "₦470,000",
    image: "/images/battery-nicd.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Nickel-Cadmium",
      capacity: "1.2kWh",
      lifespan: "2000+ cycles",
      warranty: "5 years",
    },
  },
  {
    type: "Batteries",
    name: "Flow Battery 10kWh",
    description:
      "Advanced battery with scalable capacity and long lifespan, ideal for large systems.",
    inStock: true,
    price: "₦4,500,000",
    discountPrice: "₦4,200,000",
    image: "/images/battery-flow.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Vanadium Redox Flow",
      capacity: "10kWh",
      lifespan: "10,000+ cycles",
      warranty: "15 years",
    },
  },
  {
    type: "Batteries",
    name: "Sodium-Ion Solar Battery 5kWh",
    description:
      "Next-generation solar battery, affordable alternative to lithium-ion.",
    inStock: true,
    price: "₦900,000",
    discountPrice: "₦850,000",
    image: "/images/battery-sodium.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Sodium-Ion",
      capacity: "5kWh",
      lifespan: "4000+ cycles",
      warranty: "8 years",
    },
  },
  {
    type: "Batteries",
    name: "Lead Carbon Solar Battery 150Ah",
    description:
      "Enhanced lead-acid battery with carbon additive for improved cycling.",
    inStock: true,
    price: "₦180,000",
    discountPrice: "₦165,000",
    image: "/images/battery-leadcarbon.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Lead Carbon",
      capacity: "150Ah",
      lifespan: "2500+ cycles",
      warranty: "4 years",
    },
  },
  {
    type: "Batteries",
    name: "Portable Lithium Power Station 1kWh",
    description:
      "Compact, lightweight battery pack for camping, travel, and emergencies.",
    inStock: true,
    price: "₦350,000",
    discountPrice: "₦320,000",
    image: "/images/battery-portable.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Lithium-Ion",
      capacity: "1kWh",
      lifespan: "3000+ cycles",
      warranty: "2 years",
    },
  },
];

// Inverters
export const solarInverters = [
  {
    type: "Inverters",
    name: "Hybrid Inverter 3.5kVA",
    description: "Supports both grid and solar, perfect for home use.",
    inStock: true,
    price: "₦450,000",
    discountPrice: "₦420,000",
    image: "/images/inverter3.5kva.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Hybrid",
      output: "3.5kVA",
      voltage: "48V",
      warranty: "5 years",
    },
  },
  {
    type: "Inverters",
    name: "Pure Sine Wave Inverter 5kVA",
    description: "Heavy-duty inverter designed for medium-sized businesses.",
    inStock: true,
    price: "₦650,000",
    discountPrice: "₦620,000",
    image: "/images/inverter5kva.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Pure Sine Wave",
      output: "5kVA",
      voltage: "48V",
      warranty: "5 years",
    },
  },
  {
    type: "Inverters",
    name: "Off-Grid Solar Inverter 2.5kVA",
    description:
      "Ideal for remote areas with no grid access, runs fully on solar and battery.",
    inStock: true,
    price: "₦380,000",
    discountPrice: "₦350,000",
    image: "/images/inverter-offgrid.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Off-Grid",
      output: "2.5kVA",
      voltage: "24V",
      warranty: "3 years",
    },
  },
  {
    type: "Inverters",
    name: "On-Grid String Inverter 10kW",
    description:
      "Connects solar arrays directly to the grid, widely used in commercial projects.",
    inStock: true,
    price: "₦2,200,000",
    discountPrice: "₦2,050,000",
    image: "/images/inverter-string.png",
    location: "Enugu, Nigeria",
    details: {
      type: "On-Grid String",
      output: "10kW",
      voltage: "380V",
      warranty: "8 years",
    },
  },
  {
    type: "Inverters",
    name: "Micro Inverter 350W",
    description:
      "Compact inverter attached to individual solar panels for maximum efficiency.",
    inStock: true,
    price: "₦95,000",
    discountPrice: "₦85,000",
    image: "/images/inverter-micro.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Micro Inverter",
      output: "350W",
      voltage: "230V",
      warranty: "10 years",
    },
  },
  {
    type: "Inverters",
    name: "Central Solar Inverter 500kW",
    description:
      "Large-scale inverter used for utility and industrial solar farms.",
    inStock: false,
    price: "₦120,000,000",
    discountPrice: "₦115,000,000",
    image: "/images/inverter-central.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Central Inverter",
      output: "500kW",
      voltage: "1000V",
      warranty: "10 years",
    },
  },
  {
    type: "Inverters",
    name: "Smart Solar Inverter 7.5kW",
    description:
      "Wi-Fi enabled inverter with remote monitoring and smart controls.",
    inStock: true,
    price: "₦1,200,000",
    discountPrice: "₦1,150,000",
    image: "/images/inverter-smart.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Smart Inverter",
      output: "7.5kW",
      voltage: "48V",
      warranty: "7 years",
    },
  },
  {
    type: "Inverters",
    name: "Bi-Directional Inverter 15kW",
    description:
      "Manages power both ways – from grid to battery and solar to grid.",
    inStock: true,
    price: "₦3,800,000",
    discountPrice: "₦3,600,000",
    image: "/images/inverter-bidirectional.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Bi-Directional",
      output: "15kW",
      voltage: "380V",
      warranty: "8 years",
    },
  },
];

// Appliance
export const solarAppliances = [
  {
    type: "Appliances",
    name: "Solar Water Pump 2HP",
    description:
      "Efficient solar pump for irrigation and domestic water supply.",
    inStock: true,
    price: "₦600,000",
    discountPrice: "₦550,000",
    image: "/images/solar-waterpump.png",
    location: "Enugu, Nigeria",
    details: {
      power: "2HP",
      flowRate: "2000L/hr",
      head: "120m",
      warranty: "3 years",
    },
  },
  {
    type: "Appliances",
    name: "Solar Air Conditioner 1.5HP",
    description: "Energy-efficient solar-powered AC unit for homes.",
    inStock: false,
    price: "₦900,000",
    discountPrice: "₦850,000",
    image: "/images/solar-ac.png",
    location: "Enugu, Nigeria",
    details: {
      coolingCapacity: "1.5HP",
      power: "1200W",
      warranty: "3 years",
    },
  },
  {
    type: "Appliances",
    name: "Solar Refrigerator 200L",
    description:
      "Eco-friendly DC-powered fridge for homes and small businesses.",
    inStock: true,
    price: "₦450,000",
    discountPrice: "₦420,000",
    image: "/images/solar-fridge.png",
    location: "Enugu, Nigeria",
    details: {
      capacity: "200 Liters",
      power: "150W",
      warranty: "2 years",
    },
  },
  {
    type: "Appliances",
    name: "Solar Freezer 300L",
    description:
      "Reliable solar freezer for food preservation in off-grid areas.",
    inStock: true,
    price: "₦600,000",
    discountPrice: "₦570,000",
    image: "/images/solar-freezer.png",
    location: "Enugu, Nigeria",
    details: {
      capacity: "300 Liters",
      power: "200W",
      warranty: "2 years",
    },
  },
  {
    type: "Appliances",
    name: "Solar Washing Machine 7kg",
    description: "Energy-efficient washing machine powered by solar systems.",
    inStock: true,
    price: "₦380,000",
    discountPrice: "₦350,000",
    image: "/images/solar-washer.png",
    location: "Enugu, Nigeria",
    details: {
      loadCapacity: "7kg",
      power: "500W",
      warranty: "2 years",
    },
  },
  {
    type: "Appliances",
    name: "Solar Water Heater 200L",
    description: "Durable solar water heating system for homes and hotels.",
    inStock: true,
    price: "₦480,000",
    discountPrice: "₦450,000",
    image: "/images/solar-heater.png",
    location: "Enugu, Nigeria",
    details: {
      tankCapacity: "200 Liters",
      heatingMethod: "Vacuum Tube",
      warranty: "5 years",
    },
  },
  {
    type: "Appliances",
    name: "Solar Cooker",
    description: "Portable solar-powered cooker for outdoor and rural cooking.",
    inStock: true,
    price: "₦60,000",
    discountPrice: "₦55,000",
    image: "/images/solar-cooker.png",
    location: "Enugu, Nigeria",
    details: {
      type: "Parabolic Cooker",
      temperature: "Up to 250°C",
      warranty: "1 year",
    },
  },
  {
    type: "Appliances",
    name: "Solar Television 32-inch",
    description: "Low-power DC TV for entertainment in solar-powered homes.",
    inStock: true,
    price: "₦150,000",
    discountPrice: "₦135,000",
    image: "/images/solar-tv.png",
    location: "Enugu, Nigeria",
    details: {
      screenSize: "32-inch LED",
      power: "50W",
      warranty: "2 years",
    },
  },
];

// Lighting
export const solarLightingProducts = [
  {
    type: "Lighting",
    name: "Solar Floodlight 300W",
    description: "Weatherproof LED floodlight with motion sensor.",
    inStock: true,
    price: "₦80,000",
    discountPrice: "₦70,000",
    image: "/images/solar-floodlight.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "300W LED",
      runtime: "12 hours",
      waterproof: "IP67",
      warranty: "2 years",
    },
  },
  {
    type: "Lighting",
    name: "Solar Street Light 120W",
    description: "Automatic dusk-to-dawn street lighting solution.",
    inStock: true,
    price: "₦120,000",
    discountPrice: "₦100,000",
    image: "/images/solar-streetlight.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "120W LED",
      runtime: "14 hours",
      waterproof: "IP65",
      warranty: "3 years",
    },
  },
  {
    type: "Lighting",
    name: "Solar Garden Light",
    description: "Decorative and functional lighting for gardens and pathways.",
    inStock: true,
    price: "₦15,000",
    discountPrice: "₦12,000",
    image: "/images/solar-gardenlight.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "5W LED",
      runtime: "8 hours",
      waterproof: "IP65",
      warranty: "1 year",
    },
  },
  {
    type: "Lighting",
    name: "Solar Lantern",
    description: "Portable, rechargeable lantern for home and outdoor use.",
    inStock: true,
    price: "₦10,000",
    discountPrice: "₦8,500",
    image: "/images/solar-lantern.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "3W LED",
      runtime: "10 hours",
      charging: "USB & Solar",
      warranty: "1 year",
    },
  },
  {
    type: "Lighting",
    name: "Solar Home Lighting Kit",
    description: "Complete lighting kit with bulbs and USB charging ports.",
    inStock: true,
    price: "₦65,000",
    discountPrice: "₦58,000",
    image: "/images/solar-homelightkit.png",
    location: "Enugu, Nigeria",
    details: {
      bulbs: "4 x 3W LED",
      runtime: "10 hours",
      battery: "12V Lithium",
      warranty: "2 years",
    },
  },
  {
    type: "Lighting",
    name: "Solar Wall Light",
    description: "Compact wall-mounted solar light with motion sensor.",
    inStock: true,
    price: "₦18,000",
    discountPrice: "₦15,000",
    image: "/images/solar-walllight.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "10W LED",
      runtime: "10 hours",
      waterproof: "IP65",
      warranty: "1 year",
    },
  },
  {
    type: "Lighting",
    name: "Solar Emergency Light",
    description: "Rechargeable emergency light with solar and AC charging.",
    inStock: true,
    price: "₦25,000",
    discountPrice: "₦22,000",
    image: "/images/solar-emergency.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "12W LED",
      runtime: "8–10 hours",
      charging: "AC & Solar",
      warranty: "1 year",
    },
  },
  {
    type: "Lighting",
    name: "Solar Camping Light",
    description:
      "Portable solar-powered lamp for camping and outdoor activities.",
    inStock: true,
    price: "₦20,000",
    discountPrice: "₦18,000",
    image: "/images/solar-campinglight.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "5W LED",
      runtime: "12 hours",
      charging: "USB & Solar",
      warranty: "1 year",
    },
  },
  {
    type: "Lighting",
    name: "Solar String Lights",
    description:
      "Decorative solar-powered string lights for events and gardens.",
    inStock: true,
    price: "₦12,000",
    discountPrice: "₦10,000",
    image: "/images/solar-stringlights.png",
    location: "Enugu, Nigeria",
    details: {
      length: "15m",
      modes: "8 Lighting Modes",
      runtime: "10 hours",
      waterproof: "IP65",
      warranty: "6 months",
    },
  },
  {
    type: "Lighting",
    name: "Solar High Mast Light 1000W",
    description:
      "Powerful solar lighting system for factories, stadiums, and highways.",
    inStock: true,
    price: "₦1,500,000",
    discountPrice: "₦1,350,000",
    image: "/images/solar-highmast.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "1000W LED",
      runtime: "16 hours",
      poleHeight: "12m–30m",
      waterproof: "IP67",
      warranty: "5 years",
    },
  },
  {
    type: "Lighting",
    name: "Industrial Solar Floodlight 600W",
    description:
      "Heavy-duty floodlight for warehouses, yards, and large compounds.",
    inStock: true,
    price: "₦450,000",
    discountPrice: "₦420,000",
    image: "/images/industrial-floodlight.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "600W LED",
      runtime: "12–14 hours",
      waterproof: "IP66",
      warranty: "3 years",
    },
  },
  {
    type: "Lighting",
    name: "Solar High Bay Light 200W",
    description: "Efficient high bay solar light for factories and workshops.",
    inStock: true,
    price: "₦220,000",
    discountPrice: "₦200,000",
    image: "/images/solar-highbay.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "200W LED",
      runtime: "10–12 hours",
      waterproof: "IP65",
      warranty: "3 years",
    },
  },
  {
    type: "Lighting",
    name: "Solar Canopy Light 150W",
    description:
      "Durable solar canopy light for fueling stations and outdoor businesses.",
    inStock: true,
    price: "₦180,000",
    discountPrice: "₦165,000",
    image: "/images/solar-canopy.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "150W LED",
      runtime: "12 hours",
      waterproof: "IP65",
      warranty: "3 years",
    },
  },
];

// Portable solutions
export const portableSolutions = [
  {
    type: "Portable Solutions",
    name: "Portable Solar Generator 1000W",
    description: "Compact generator for camping and small appliances.",
    inStock: true,
    price: "₦300,000",
    discountPrice: "₦270,000",
    image: "/images/solar-generator.png",
    location: "Enugu, Nigeria",
    details: {
      capacity: "1000W",
      battery: "1kWh Lithium-Ion",
      ports: "AC/DC/USB outputs",
      warranty: "2 years",
    },
  },
  {
    type: "Portable Solutions",
    name: "Foldable Solar Charger 100W",
    description: "Portable charger for phones, tablets, and small gadgets.",
    inStock: true,
    price: "₦45,000",
    discountPrice: "₦38,000",
    image: "/images/foldable-charger.png",
    location: "Enugu, Nigeria",
    details: {
      output: "100W",
      weight: "3kg",
      waterproof: "IP65",
      warranty: "1 year",
    },
  },
  {
    type: "Portable Solutions",
    name: "Solar Power Bank 30,000mAh",
    description: "Dual USB outputs, perfect for travel and emergencies.",
    inStock: true,
    price: "₦25,000",
    discountPrice: "₦20,000",
    image: "/images/solar-powerbank.png",
    location: "Enugu, Nigeria",
    details: {
      capacity: "30,000mAh",
      ports: "2x USB-A, 1x USB-C",
      waterproof: "IP54",
      warranty: "1 year",
    },
  },
  {
    type: "Portable Solutions",
    name: "Solar Camping Lantern",
    description: "Rechargeable lantern with USB charging port.",
    inStock: true,
    price: "₦12,000",
    discountPrice: "₦9,500",
    image: "/images/solar-lantern.png",
    location: "Enugu, Nigeria",
    details: {
      brightness: "500 lumens",
      runtime: "20 hours",
      charging: "Solar/USB",
      warranty: "6 months",
    },
  },
  {
    type: "Portable Solutions",
    name: "Backpack with Solar Panel 15W",
    description: "Travel backpack with built-in solar charging panel.",
    inStock: true,
    price: "₦35,000",
    discountPrice: "₦30,000",
    image: "/images/solar-backpack.png",
    location: "Enugu, Nigeria",
    details: {
      panel: "15W Monocrystalline",
      capacity: "25L",
      outputs: "USB charging",
      warranty: "1 year",
    },
  },
  {
    type: "Portable Solutions",
    name: "Mini Solar Fan with Light",
    description: "Portable fan with built-in solar panel and LED lamp.",
    inStock: true,
    price: "₦18,000",
    discountPrice: "₦15,000",
    image: "/images/solar-fan.png",
    location: "Enugu, Nigeria",
    details: {
      fanSpeed: "3 levels",
      runtime: "10 hours",
      battery: "Rechargeable Lithium",
      warranty: "6 months",
    },
  },
  {
    type: "Portable Solutions",
    name: "Foldable Solar Panel 300W",
    description: "Heavy-duty portable panel for camping and RVs.",
    inStock: true,
    price: "₦200,000",
    discountPrice: "₦180,000",
    image: "/images/foldable-panel.png",
    location: "Enugu, Nigeria",
    details: {
      output: "300W",
      weight: "9kg",
      waterproof: "IP65",
      warranty: "2 years",
    },
  },
  {
    type: "Portable Solutions",
    name: "Portable Solar Refrigerator 60L",
    description: "Solar-powered fridge/freezer for camping and trips.",
    inStock: true,
    price: "₦420,000",
    discountPrice: "₦390,000",
    image: "/images/solar-fridge.png",
    location: "Enugu, Nigeria",
    details: {
      capacity: "60 Liters",
      runtime: "Up to 24 hours",
      battery: "Built-in Lithium",
      warranty: "2 years",
    },
  },
];

// CTA
export const solarProducts = [
  {
    type: "Panels",
    name: "Mono-Crystalline Solar Panel 350W",

    image: "/solarpanelimg.webp",
  },
  {
    type: "Batteries",
    name: "Lithium-Ion Solar Battery 5kWh",

    image: "/solarbatteriesimg.webp",
  },
  {
    type: "Inverters",
    name: "Hybrid Inverter 3.5kVA",

    image: "/solarinverterimg.webp",
  },
  {
    type: "Appliances",
    name: "Solar Water Pump 2HP",

    image: "/solarapplianceimg.webp",
  },
  {
    type: "Lighting",
    name: "Solar Floodlight 300W",

    image: "/solarlightingimg.webp",
  },
  {
    type: "Portable Solutions",
    name: "Portable Solar Generator 1000W",

    image: "/solarportable.webp",
  },
];
